export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
export const ADD_HERO = 'ADD_HERO'
export const SET_HERO_DATA = 'SET_HERO_DATA'
export const CLEAR_HERO_DATA = 'CLEAR_HERO_DATA'